Repository wecode-bootcamp-korea/30-2nd-README-frontend, pull requests merged in 2022-03, with the labels that each got.

#2 [30기 한영현] 공통 폰트 수정
  src/pages/Main/Main.js
  src/styles/fonts/NanumGothic-Bold.ttf
  src/styles/fonts/NanumGothic-ExtraBold.ttf
  src/styles/fonts/NanumGothic-Regular.ttf
  src/styles/fonts/NotoSansKR-Black.woff
  src/styles/fonts/NotoSansKR-Bold.woff
  src/styles/fonts/NotoSansKR-Light.woff
  src/styles/fonts/NotoSansKR-Medium.woff
  src/styles/fonts/NotoSansKR-Regular.woff
  src/styles/fonts/NotoSansKR-Thin.woff
  src/styles/fonts/fonts.js
Labels: Status: 리뷰 요청

#3 [30기 이희수][Nav] Nav 구현 완료
  package-lock.json
  package.json
  public/images/bell.png
  public/images/cart.png
  public/images/library.png
  public/images/logo.png
  public/images/magnifier.png
  public/images/user.png
  src/components/Nav/Nav.js
Labels: Status: Accepted

#12 [30기 이희수][Nav] padding 수정 (최종 수정)
  src/components/Nav/Nav.js
Labels: Status: Rebase 요청

#10 [30기 이희수][Footer] Conflict 해결 완료
  src/components/Footer/Footer.js
  src/components/Footer/FooterData.js
Labels: Status: Rebase 요청

#11 [30기 한영현] 전체 폰트 스타일 수정 완료
  public/index.html
  src/styles/GlobalStyle.js
Labels: Status: 리뷰 요청

#5 [30기 이희수] [Main] 상세페이지로 이동하는 기능 구현 중
  package-lock.json
  package.json
  public/images/banner1.png
  public/images/banner2.png
  public/images/banner3.png
  public/images/comedy.png
  public/images/detective.png
  public/images/discovery.png
  public/images/fantasy.png
  public/images/horror.png
  public/images/romance.png
  public/images/science.png
  public/images/wuxia.png
  src/Router.js
  src/pages/Main/BestSellerList.js
  src/pages/Main/Book.js
  src/pages/Main/BookList.js
  src/pages/Main/CategoryBarData.js
  src/pages/Main/CategoryBook.js
  src/pages/Main/CategoryBookList.js
  src/pages/Main/Main.js
  src/pages/Main/MdPickList.js
  src/pages/Main/RecommendList.js
  src/pages/Main/Slide/Slide.js
  src/pages/Main/Slide/slick-theme.css
  src/pages/Main/Slide/slick.css
  src/pages/Main/TitleBar.js
Labels: Status: Rebase 요청

#7 [30기 한영현] 상세 페이지 구현완료
  public/data/productListData.json
  src/components/Nav/Nav.js
  src/pages/Login/Login.js
  src/pages/Product/CheckInput.js
  src/pages/Product/Product.js
  src/pages/Product/SeriesData.js
  src/pages/Product/UserComment.js
  src/pages/Product/ViewMore.js
Labels: Status: 리뷰 요청
